### PR TITLE
added Catallaxy to the official OTS servers

### PR DESCRIPTION
**Pull request by cloutier**

### CODE REVIEW

**Comment by FrancisPouliot** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Concept ACK!  Catallaxy intends to support the OpenTimestamps Project in any way we can and we are deploying software that is intended to be used by Auditors and the legal system. We intended to run this well-financed for a very long time and maintain excellent uptime ;) 

For the record, I am on of the co-founders of Catallaxy

verify at keybase.io/verify
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.76
Comment: https://keybase.io/crypto

wsBcBAABCgAGBQJalrWEAAoJEOppJT/UFvt7pyEH/jveMFHUQ8EiFG1hYt9RWMTK
5UvcdZCmfik71TiifjtYp+geER0jCnapb0V5XYGFMJcuo5zruwmCx9UHFpp+fNKz
6knhrsZ2+yS4Z7rOIbVLUNgxHvYpqmsOuAJU7HZmDP4lOzzjZ1iNxgvQa2mZnC8Q
rf6NCjxfRxqGlAPwmE/1Gn1doVSRXvU0fUoRx21fYmJ25ds5wc1fDkwHF5xkMw7t
1PRG5RF5inQNMZaMKxeI6s4BlkS3IKQBFIDEGNE1s/ZZ7HrG1ecJLOTjn7oxGhwp
7toyi5ZYPmHHuzMUxx5MVTSLMfcXNQYv3P/DSwKI88Xg7RVwJCIfbns2nY2V2r0=
=NSD4
-----END PGP SIGNATURE-----

**Comment by petertodd** [comment]
Looks like `https://ots.btc.catallaxy.com/` isn't working yet; I don't see it actually making any transactions.

Also, you need to add the server to the whitelist, not just the list of servers used when creating a timestamp.

**Comment by cloutier** [comment]
My bad, there was a bech32 output in my wallet and ots didn't quite like that, I'm consolidating right now to a P2SH-P2WPKH address. This should teach me not to make breaking changes right before a PR... 

As soon as this is mined, this server should work just as before.

**Comment by petertodd** [comment]
Maybe that tx is still unmined, but it still doesn't appear to be working.

Note that you have to have Core v0.16.0 setup to return P2SH - not bech32 - addresses in the RPC; python-bitcoinlib doesn't yet support bech32 addresses.

**Comment by cloutier** [comment]
The tx mined over night, sorry about that, the server is running smoothly now.

I'm doing another PR right now for the whitelist.

**Comment by petertodd** [comment]
FWIW, I'm stress testing it right now, and we also added that server to our monitoring scripts to check reliability.

**Comment by cloutier** [comment]
I was about to ban your IP ;)

Is rate limiting per IP is something that was discussed or planned?

**Comment by petertodd** [comment]
`otsd` is designed to run behind a caching server such as nginx; better to do rate limiting at that level.

Also, rate limiting is something you should avoid due to Tor and similar things; one IP ≠ one user.

**Pull request merged**
