### PR TITLE
adding sh wrapper to file installed in PATH by pip

### PR DESCRIPTION
**Pull request by RCasatta**
This adds the sh wrapper to integrate ots in git with only the pip installation.

### CODE REVIEW

**Comment by petertodd** [comment]
Two issues:

1. Should it have the `.sh` extension? I don't see why.
2. I think we should make `--rehash-trees` be used by default now. Any objections?

**Comment by RCasatta** [comment]
> Should it have the .sh extension? I don't see why.

Maybe I am missing something. @AdamISZ was interested in stamping his commits, we installed opentimestamps-client through pip. The pip package expose the python executables `ots` and `ots-git-wrapper`. With git config we added to `gpg.program` the `ots-git-wrapper` but when trying to commit we had an error. I remembered we should use the `.sh`  for that because, as written in the file itself:
```
# Required because git's gpg.program option doesn't allow you to set command
# line options; see the doc/git-integration.md
```
To temporary solve the issue we had to git clone the project and use the `ots-git-wrapper.sh` and everything works. That's why I thought to expose also the `.sh` in the pip installation.

We maybe should had also a `.bat` for windows users, so for this reasons, yes I think we need the `.sh` extension

> I think we should make --rehash-trees be used by default now. Any objections?

Agree

**Comment by petertodd** [comment]
Oh, windows users I hadn't thought about... Actually that suggests that the wrapper script maybe should be a *Python* program rather than a shell script, to avoid depending on bash. But I don't know much about how Windows users use OTS.

Note that the command line options for ots-git-wrapper could also be stored in a config file, which the wrapper script ends up being used as. That's probably a better approach overall.

**Comment by RCasatta** [comment]
Closing this since the new `setup.py` script is launching python files directly

**Pull request closed without merging**
