### PR TITLE
Adding finney as default calendar server

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by petertodd** [comment]
Two issues:

1. The URL in the PendingAttestation's returned by this calendar is incorrect; it should be https://finney.calendar.eternitywall.it (note how ots verify complains that the calendar isn't in the whitelist)
2. The URL used to *submit* digests should be separate from the URL of the calendar itself. The rational here is those are actually two separate functions: timestamp aggregation and calendar lookup. It's just an implementation detail that the same server happens to do both right now.

I'd suggest you create a separate a.pool.eternitywall.it domain, pointing to the same same server as finney.calendar.eternitywall.it, matching the setup on the alice/bob servers.

**Comment by RCasatta** [comment]
1. URL in PendingAttestation fixed
2. using _a.pool.eternitywall.com_ for submit as suggested

**Comment by petertodd** [comment]
Merged!

Note that I also changed the timeout behavior in https://github.com/opentimestamps/opentimestamps-client/commit/0a14ea8101dcf310dec2372c2e743ab0a588ce39 to wait for all aggregation servers to respond within the timeout period; the previous short-circuit logic would mean that here in North America the finney calendar wasn't being used because it responded slower than alice and bob.

**Comment by RCasatta** [comment]
With 0a14ea8101dcf310dec2372c2e743ab0a588ce39 is the logic of _m of n_ working as expected?
`ots stamp -m 1 README.md` returns an ots with 3 calendar, I was expecting to return an ots with just one calendar (the fastest to answer)

**Comment by petertodd** [comment]
Ah, yes, that's working as expected, but perhaps my expectation doesn't make sense. :)

So, my thinking is the `-m` option is a safety threshold: getting fewer timestamps than that number should be a hard error. But if the servers do respond, great! Might as well use the timestamps.

Meanwhile, if you did want a timestamp with just one calendar, you'd do it by specifying fewer servers; why wastefully contact all three if you're only planning on using one calendar anyway?

Maybe if there's strong demand for smaller timestamps we could have a `-n` option which has the behavior of reducing the number of timestamps. It could even have logic where it'd try different calendars in succession.

But I am worried that all the above will be too hard for users to understand. :(

**Pull request merged**
