### PR TITLE
PEP8 and gitignore

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by petertodd** [comment]
Need a rebase!

I, er, kinda rewrote stuff... :)

**Comment by RCasatta** [comment]
much stuff!

**Comment by petertodd** [comment]
Heh, and needs yet another rebase... maybe submit your .gitignore thing as a different pull. :)

**Comment by RCasatta** [comment]
rebased, let's see if merge this time :)

**Comment by petertodd** [comment]
Done!

**Pull request merged**
