### PR TITLE
Allow stamp to use stdin/stdout instead of explicit files

### PR DESCRIPTION
**Pull request by gwillen**

### CODE REVIEW

**Comment by gwillen** [comment]
I thought about something like a -o option for output file, but that's tricky with multiple input files. It's a bit weird to be outputting binary data to stdout but I'd feel even weirder changing the output format based on the destination.

**Comment by petertodd** [comment]
FYI, going to get to take a look at this after next Monday. Sorry for the wait!

**Comment by gwillen** [comment]
No problem! This was pretty much a one-off for the RWoT workshop and it's not clear that the stuff we wrote there has any future, so please consider this an offering of a useful feature if you want it, but not if you don't.

**Comment by petertodd** [comment]
Thanks!

Might change this later to the more standard '-' for input and output, but it's a good start.

**Pull request merged**
