### PR TITLE
Updates to include python-opentimestamps lib as requirement instead of by file inclusion

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by petertodd** [comment]
NACK

However we reference that repo, we need to do it via commit hash to make sure the result is deterministically reproducable.

**Comment by RCasatta** [comment]
requirements.txt manage to reference to a specific hash, for example:

`-e git+https://github.com/opentimestamps/python-opentimestamps.git@454118ff8372cee9fb3af6baba47f0df745961a7#egg=opentimestamps`

is this ok?

**Comment by petertodd** [comment]
Seems error prone to me. :(

Does a symlink to python-opentimestamps/opentimestamps work in your IDE?

**Comment by RCasatta** [comment]
ok.
yes, the symlink works. I made another pull request https://github.com/opentimestamps/opentimestamps-client/pull/3

**Pull request closed without merging**
